name: build-and-test

on:
  push:
    branches: [main]

env:
  DOTNET_VERSION: "6.0.x"
  DOTNET_NOLOGO: true

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Run Server
        run: dotnet run --project ./GitHubActionsBackGroundTest/GitHubActionsBackGroundTest.csproj &

      - name: Test
        run: dotnet test ./TestProject1/TestProject1.csproj
